language: node_js
sudo: false
git:
    depth: 3
node_js:
    - "8"

install:
    - yarn

before_script:
    # Unencrypt and set id_rsa keys
    - openssl aes-256-cbc -K $encrypted_b7491ecaf904_key -iv $encrypted_b7491ecaf904_iv -in ./deploy/travis_rsa.tar.enc -out ./deploy/travis_rsa.tar -d
    - tar xvf ./deploy/travis_rsa.tar
    - cp ./travis_rsa ~/.ssh/id_rsa
    - cp ./travis_rsa.pub ~/.ssh/id_rsa.pub
    - sudo chmod 600 ~/.ssh/*
    - eval `ssh-agent -s`
    - ssh-add ~/.ssh/id_rsa
    # Set git info
    - git config user.name "Travis CI Automation"
    - git config user.email "deuxmotoautomation@gmail.com"

script: # no tests yet...maybe one day
    - cd ./deploy
    - ./deploy.js

after_success:
    - echo "Deployment success"
after_failure:
    - echo "Deployment failure :'("
