language: node_js
sudo: false
git:
    depth: 3
node_js:
    - "8"

install:
    - npm install @angular/cli

before_script:
    - openssl aes-256-cbc -K $encrypted_b7491ecaf904_key -iv $encrypted_b7491ecaf904_iv -in ./deploy/travis_rsa.tar.enc -out ./deploy/travis_rsa.tar -d
    - tar xvf ./deploy/travis_rsa.tar
    - cp ./travis_rsa ~/.ssh/id_rsa
    - cp ./travis_rsa.pub ~/.ssh/id_rsa.pub
    - sudo chmod 600 ~/.ssh/*
    - eval `ssh-agent -s`
    - ssh-add ~/.ssh/id_rsa

script: # no tests yet...maybe one day
    - ./deploy.sh

after_success:
    - echo "Deployment success"
after_failure:
    - echo "Deployment failure :'("
