language: node_js
sudo: false
git:
    depth: 3
node_js:
    - "8"

install: true # no installation step yet

before_script:
    - openssl aes-256-cbc -K $encrypted_b7491ecaf904_key -iv $encrypted_b7491ecaf904_iv -in ./deploy/travis_rsa.enc -out ./deploy/travis_rsa -d
    - openssl aes-256-cbc -K $encrypted_b7491ecaf904_key -iv $encrypted_b7491ecaf904_iv -in ./deploy/travis_rsa.pub.enc -out ./deploy/travis_rsa.pub -d
    - cp ./travis_rsa > ~/.ssh/id_rsa
    - cp ./travis_rsa.pub > ~/.ssh/id_rsa.pub
    - sudo chmod 600 ~/.ssh/*
    - ssh-add ~/.ssh/id_rsa

script: # no tests yet...maybe one day
    - ./deploy.sh

after_success:
    - echo "Deployment success"
after_failure:
    - echo "Deployment failure :'("
