language: node_js
sudo: false
git:
    depth: 3
node_js:
    - "8"

install: true # no installation step yet

script: # no tests yet...maybe one day
    - cd ./deploy && ./deploy.sh

after_success:
    - echo "Deployment success"
after_failure:
    - echo "Deployment failure :'("
